### ISSUE TITLE
Fix Issues while scrolling with only shotgun in inventory

### ISSUE THREAD

**Issue by mcdonaldduncan** [mcdonaldduncan/Freebooter#223] opened 2023-03-14 23:29 UTC
errors when attempting to switch weapons while only having the shotgun

![Image](https://user-images.githubusercontent.com/72177724/225164537-fcaebd34-5c02-4663-8afa-08c7281637e4.png)

**Comment by Sebp23** [comment] 2023-03-14 23:43
Not able to reproduce this error in any of the levels. Do you have more specific reproduction steps?

**Comment by mcdonaldduncan** [comment] 2023-03-14 23:47
@Sebp23 it happens on all of the levels, if it is not happening for you check to see if you have changes that have not been pushed

**Comment by mcdonaldduncan** [comment] 2023-03-14 23:48
As far as replication, I go to any of the levels and scroll up on the mousewheel

**Comment by Sebp23** [comment] 2023-03-14 23:51
Ok so it happens only if you scroll up first. I'll look into it, should be a quick fix.

**Comment by Sebp23** [comment] 2023-03-14 23:57
Fixed in commit

**Closed by Sebp23** 2023-03-14 23:57 UTC
Labels: bug
